GET http://localhost:3003/ping
###

GET http://localhost:3003/users
###

GET http://localhost:3003/products
###

POST http://localhost:3003/users
Content-Type: application/json

{
    "id": "u005",
    "name": "Astrodev",
    "email": "astrodev@email.com",
    "password": "astrodev00"
}
###

POST http://localhost:3003/products
Content-Type: application/json

{
    "id": "p003",
    "name": "nave mae",
    "price": 2000000,
    "description": "nave gigante",
    "image_url": "https://picsum.photos/seed/Teclado%20gamer/400"
}
###

DELETE http://localhost:3003/users/u002
###

DELETE http://localhost:3003/products/p002
###

PUT http://localhost:3003/users/u004
Content-Type: application/json

{
    "name": "Marciano"
}
###

PUT http://localhost:3003/products/p004
Content-Type: application/json

{
    "name": "nave a outra"
}
###