GET http://localhost:3003/ping
###

GET http://localhost:3003/users
###

GET http://localhost:3003/products?name=nave
###

GET http://localhost:3003/purchases/P001
###

POST http://localhost:3003/users
Content-Type: application/json

{
    "id": "u005",
    "name": "Astrodev",
    "email": "astrodev@email.com",
    "password": "astrodev00"
}
###

POST http://localhost:3003/products
Content-Type: application/json

{
    "id": "p002",
    "name": "nave mae",
    "price": 2000000,
    "description": "nave gigante",
    "image_url": "https://picsum.photos/seed/Teclado%20gamer/400"
}
###

POST http://localhost:3003/purchases
Content-Type: application/json

{
    "id": "P006",
    "buyer": "u003",
    "total_price": 2136845
}
###


DELETE http://localhost:3003/users/u002
###

DELETE http://localhost:3003/products/p002
###

DELETE http://localhost:3003/purchases/P002
###

PUT http://localhost:3003/users/u004
Content-Type: application/json

{
    "name": "Marciano"
}
###

PUT http://localhost:3003/products/p004
Content-Type: application/json

{
    "name": "nave a outra"
}
###